import yaml
from tao_lab.methods.base import AnalysisResult

def generate_markdown_report(result: AnalysisResult, narration: str) -> str:
    """
    Generate a standardized Markdown report from an AnalysisResult.
    """
    report = f"""# Tao Lab Experiment Report
## Analysis Overview
- **Method:** {result.method_name}
- **SRM Check:** {"⚠️ FAILED" if result.srm_detected else "✅ PASSED"} (p={result.srm_p_value:.4f})

## Executive Summary
{narration}

## Statistical Findings
| Metric | Absolute Lift | 95% Confidence Interval | Significant |
|:-------|:--------------|:------------------------|:------------|
"""
    for m in result.metrics:
        sig_flag = "⭐ YES" if m.is_significant else "NO"
        report += f"| {m.metric_name} | {m.lift_absolute:.4f} | [{m.ci_lower:.3f}, {m.ci_upper:.3f}] | {sig_flag} |\n"
        
    report += f"""
---
## Configuration (Reproducibility)
```yaml
{yaml.dump(result.config_snapshot.model_dump())}
```

*Report generated by Tao Lab.*
"""
    return report
